export enum ErrorCode {
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  EMAIL_DUPLICATED = "EMAIL_DUPLICATED",
  NOT_MATCH_PASSWORD_COMPLEXITY_RULES = "NOT_MATCH_PASSWORD_COMPLEXITY_RULES",
}
